CREATE TABLE [dbo].[TBL_PRODUCTO] (
    [PROD_INT_ID]    UNIQUEIDENTIFIER CONSTRAINT [DF__TBL_PRODU__PROD___1DE57479] DEFAULT (newid()) NOT NULL,
    [PROD_NOMBRE]    VARCHAR (100)    NULL,
    [PROD_SYS_NAME]  VARCHAR (50)     NULL,
    [PROD_PRE_V]     DECIMAL (18, 2)  NULL,
    [PROD_PRE_C]     DECIMAL (18, 2)  NULL,
    [PROD_CANT]      INT              NULL,
    [CAT_INT_ID]     UNIQUEIDENTIFIER NOT NULL,
    [USE_INF_INT_ID] UNIQUEIDENTIFIER CONSTRAINT [DF__TBL_PRODU__USE_I__1ED998B2] DEFAULT (newid()) NOT NULL,
    [PROD_STATUS]    BIT              NULL,
    CONSTRAINT [PK__TBL_PRODUCTO__145C0A3F] PRIMARY KEY CLUSTERED ([PROD_INT_ID] ASC),
    CONSTRAINT [FK_TBL_PRODUCTO] FOREIGN KEY ([CAT_INT_ID]) REFERENCES [dbo].[CAT_CATEGORIA] ([CAT_INT_ID])
);

